require 'coffee-script/register'
utils = require './build/utils'
target = require './build/target'

require './build/css'
require './build/js'
require './build/html'
require './build/s3'
require './build/server'
require './build/data'
