// Generated by CoffeeScript 1.6.3
var home;

home = function(req, res) {
  return res.render('index');
};

exports.create = function(app) {
  app.get('/', home);
  require('./prompts').create(app);
  require('./schools').create(app);
  require('./users').create(app);
  return require('./postcards').create(app);
};
